### ISSUE TITLE
No matching version found for @react-navigation/core@3.0.0-alpha

### ISSUE THREAD

**Issue by zhangjianlin77** [react-navigation/example-web#1]
How can I run the demo.

**Comment by zhangjianlin77** [comment]
"@react-navigation/core": "^3.0.0",
    "@react-navigation/web": "^1.0.0-alpha.7",

**Comment by RodolfoGS** [comment]
> @react-navigation/core

thanks! 👍

**Comment by sumitkharche** [comment]
@RodolfoGS Current project has older versions of below libraries. 
`"@react-navigation/core": "3.0.0-alpha",`
`"@react-navigation/web": "^1.0.0-alpha",`
Can I update it to latest versions:
`"@react-navigation/core": "^3.0.0",`
 `"@react-navigation/web": "^1.0.0-alpha.9",`
